# Generated by Django 6.0.6 on 2026-06-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='title',
        ),
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
        migrations.AlterField(
            model_name='story',
            name='character',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='keywords',
            field=models.CharField(max_length=500),
        ),
    ]
