# Generated by Django 6.0.6 on 2026-06-19 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_story_title_remove_story_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='keywords',
        ),
        migrations.AddField(
            model_name='story',
            name='keyword',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='timezone.now', max_length=200),
            preserve_default=False,
        ),
    ]
