# Generated by Django 6.0.6 on 2026-06-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_story_keywords_story_keyword_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='age_group',
            field=models.CharField(default='children', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='length',
            field=models.CharField(default='medium', max_length=50),
        ),
    ]
